chart_config:
  supported_resolutions:
    - "1"
    - "3"
    - "5"
    - "15"
    - "30"
    - "60"
    - "120"
    - "240"
    - "360"
    - "480"
    - "1D"
    - "3D"
    - "1W"
    - "2W"
    - "1M"
sync_interval: 1800
batch_days: 25
reset_db: false
