apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: core
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: go-server
          image: ghcr.io/imerkle/balancer-view:latest
          env:
            - name: POSTGRES_CONN
              value: "postgres://postgres:postgres@postgres-service.core.svc.cluster.local:5432/postgres"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: core
spec:
  type: ClusterIP
  selector:
    app: go-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: core
  name: go-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: balancerviewserver.192.168.39.35.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-server-service
                port:
                  number: 80
