name: Docker build and gitops
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.CR_PAT }}
          image: ${{ github.repository }}
          tag: ${{ github.sha }}
      - uses: actions/checkout@master
        with:
          repository: imerkle/balancer-view
          path: balancer-view
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Get yq
        uses: mikefarah/yq@v4.6.3
        run: |
          yq --version
          yq w k8s/app.yaml 'spec.template.spec.containers[0].image' ${{ github.repository }}:${{ github.sha }} > k8s/accounts_tmp.yaml
          mv k8s/app.yaml k8s/app.yaml
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
