name: Docker build and gitops
on: push
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.CR_PAT }}
          image: ${{ github.repository }}
          tag: ${{ github.sha }}
  gitops:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@master
        with:
          repository: imerkle/balancer-view
          path: balancer-view
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Update image tag
        uses: loveholidays/gitops-action-yaml-updater@v1.0
        with:
          mode: IMAGE_TAG
          container-name: go-server
          new-image-tag: ${{ github.sha }}
          filepath: balancer-view/k8s/app.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
